/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Principal = IDL.Principal;
export const AttendanceSession = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'photoUrl' : IDL.Text,
  'villageId' : IDL.Nat,
  'teacherId' : Principal,
  'timestamp' : IDL.Int,
});
export const Village = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'villageId' : IDL.Nat,
  'rollNo' : IDL.Text,
});
export const AttendanceRecord = IDL.Record({
  'status' : IDL.Text,
  'studentId' : IDL.Nat,
  'sessionId' : IDL.Nat,
});
export const TeacherProfile = IDL.Record({
  'userId' : Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'villageId' : IDL.Nat,
});
export const VillageStats = IDL.Record({
  'totalSessions' : IDL.Nat,
  'studentCount' : IDL.Nat,
});
export const AttendanceInput = IDL.Record({
  'status' : IDL.Text,
  'studentId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudent' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Result], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTeacher' : IDL.Func(
      [Principal, IDL.Nat, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'createVillage' : IDL.Func([IDL.Text], [Result], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [Result], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(AttendanceSession)], ['query']),
  'getAllVillages' : IDL.Func([], [IDL.Vec(Village)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getMyVillage' : IDL.Func([], [Village], ['query']),
  'getSessionRecords' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getSessions' : IDL.Func([IDL.Nat], [IDL.Vec(AttendanceSession)], ['query']),
  'getStudents' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
  'getTeachers' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
  'getVillageStats' : IDL.Func([IDL.Nat], [VillageStats], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(AttendanceInput)],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Principal = IDL.Principal;
  const AttendanceSession = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'photoUrl' : IDL.Text,
    'villageId' : IDL.Nat,
    'teacherId' : Principal,
    'timestamp' : IDL.Int,
  });
  const Village = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'villageId' : IDL.Nat,
    'rollNo' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'status' : IDL.Text,
    'studentId' : IDL.Nat,
    'sessionId' : IDL.Nat,
  });
  const TeacherProfile = IDL.Record({
    'userId' : Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'villageId' : IDL.Nat,
  });
  const VillageStats = IDL.Record({
    'totalSessions' : IDL.Nat,
    'studentCount' : IDL.Nat,
  });
  const AttendanceInput = IDL.Record({
    'status' : IDL.Text,
    'studentId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudent' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Result], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTeacher' : IDL.Func(
        [Principal, IDL.Nat, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'createVillage' : IDL.Func([IDL.Text], [Result], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [Result], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(AttendanceSession)], ['query']),
    'getAllVillages' : IDL.Func([], [IDL.Vec(Village)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getMyVillage' : IDL.Func([], [Village], ['query']),
    'getSessionRecords' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getSessions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceSession)],
        ['query'],
      ),
    'getStudents' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
    'getTeachers' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
    'getVillageStats' : IDL.Func([IDL.Nat], [VillageStats], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(AttendanceInput)],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };