/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceInput { 'status' : string, 'studentId' : bigint }
export interface AttendanceRecord {
  'status' : string,
  'studentId' : bigint,
  'sessionId' : bigint,
}
export interface AttendanceSession {
  'id' : bigint,
  'date' : string,
  'photoUrl' : string,
  'villageId' : bigint,
  'teacherId' : Principal,
  'timestamp' : bigint,
}
export type Principal = Principal;
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface Student {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
  'villageId' : bigint,
  'rollNo' : string,
}
export interface TeacherProfile {
  'userId' : Principal,
  'name' : string,
  'email' : string,
  'villageId' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Village { 'id' : bigint, 'name' : string }
export interface VillageStats {
  'totalSessions' : bigint,
  'studentCount' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudent' : ActorMethod<[bigint, string, string], Result>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignTeacher' : ActorMethod<[Principal, bigint, string, string], Result>,
  'createVillage' : ActorMethod<[string], Result>,
  'deleteStudent' : ActorMethod<[bigint], Result>,
  'getAllSessions' : ActorMethod<[], Array<AttendanceSession>>,
  'getAllVillages' : ActorMethod<[], Array<Village>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyStudents' : ActorMethod<[], Array<Student>>,
  'getMyVillage' : ActorMethod<[], Village>,
  'getSessionRecords' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getSessions' : ActorMethod<[bigint], Array<AttendanceSession>>,
  'getStudents' : ActorMethod<[bigint], Array<Student>>,
  'getTeachers' : ActorMethod<[], Array<TeacherProfile>>,
  'getVillageStats' : ActorMethod<[bigint], VillageStats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitAttendance' : ActorMethod<
    [string, string, Array<AttendanceInput>],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];